# Remove a linha 'version' que é obsoleta
services:
  # 1. Serviço do Banco de Dados (sem alterações)
  db:
    image: mysql:8.0
    container_name: quiz-enem-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - quiz-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Serviço da Aplicação Java
  app:
    build: .
    container_name: quiz-enem-app
    restart: always
    # A secção 'ports' foi REMOVIDA daqui. O Nginx agora lida com o tráfego externo.
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quiz-net

  # 3. NOVO Serviço Nginx (Proxy Reverso para HTTPS)
  nginx:
    image: nginx:latest
    container_name: quiz-enem-proxy
    restart: always
    ports:
      - "80:80"    # Expõe a porta 80 para o desafio do Let's Encrypt
      - "443:443"  # Expõe a porta 443 para o tráfego HTTPS
    volumes:
      # Mapeia os ficheiros de configuração e certificados para dentro do container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - app
    networks:
      - quiz-net

# Define os volumes e a rede
volumes:
  mysql-data:

networks:
  quiz-net:
