version: '3.8'

services:
  # 1. O serviço para o banco de dados MySQL (COM A VERIFICAÇÃO DE SAÚDE)
  db:
    image: mysql:8.0
    container_name: quiz-enem-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - quiz-net
    # ▼▼▼ ADIÇÃO IMPORTANTE ABAIXO ▼▼▼
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. O serviço para a sua aplicação Java (COM UMA PEQUENA MUDANÇA)
  app:
    build: .
    container_name: quiz-enem-app
    restart: always
    ports:
      - "80:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
    # ▼▼▼ MUDANÇA IMPORTANTE AQUI ▼▼▼
    # Agora, a aplicação espera que o serviço 'db' esteja "saudável"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quiz-net

volumes:
  mysql-data:

networks:
  quiz-net: