version: '3.8'

services:
  # Serviço para o banco de dados MySQL
  db:
    image: mysql:8.0
    container_name: quiz-enem-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - quiz-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço para a sua aplicação Java
  app:
    build: .
    container_name: quiz-enem-app
    restart: always
    # A porta não é mais exposta para o mundo exterior.
    # O Nginx irá se comunicar com ela internamente.
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quiz-net

  # Serviço do Nginx (Reverse Proxy)
  nginx:
    image: nginx:latest
    container_name: quiz-enem-nginx
    restart: always
    ports:
      - "80:80"   # Expõe a porta HTTP
      - "443:443" # Expõe a porta HTTPS
    volumes:
      # CORREÇÃO: Monta o arquivo default.conf no diretório correto conf.d
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    depends_on:
      - app
    networks:
      - quiz-net

  # Serviço do Certbot para certificados SSL
  certbot:
    image: certbot/certbot
    container_name: quiz-enem-certbot
    volumes:
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  mysql-data:

networks:
  quiz-net:
